language: generic
sudo: false
dist: trusty

notifications:
  email: false

addons:
  apt:
    packages:
      - opam

install:
  - export OPAMROOT=~/opam-coq.8.6
  - opam init -n --comp=4.01.0
  - opam repo add coq-released http://coq.inria.fr/opam/released
  - opam install coq.8.6 && opam pin add coq 8.6

  - eval `opam config env`

script:
  - coqc -v
  - coqc object.v
